export const EN: {} = {
  'BASE_INFO_TITLE': 'BASE',
  'save_txt': 'Save',
  'cancel_txt': 'Cancel',
  'go_back_txt': 'Go Back',
  'detail_txt': 'Detail',
  'start_txt': 'Start',
  'stop_txt': 'Stop',

  'login_page_title': 'LOGIN',
  'welcome_text':'Welcome!',
  'login_text':'Login',
  'ph_name_txt':'Please input account',
  'ph_pwd_txt':'Please input password',

  'dashboard_page_title': 'Home Page',
  'stocking_txt':'Warehouse Management',
  'in_stock_txt':'在库管理',
  'dbd_space_management_txt':'库区管理',
  'dbd_shelf_management_txt':'货架管理',
  'dbd_location_management_txt':'货位管理',
  'dbd_instock_info_txt':'在库信息',
  'dbd_inbound_txt':'入库管理',
  'dbd_outbound_txt':'出库管理',
  'dbd_checking_txt':'盘点管理',
  'dbd_wastage_txt':'损耗管理',
  'dbd_item_move_txt':'移动商品',

  'dbd_task_management_txt':'任务管理',
  'dbd_task_list_txt':'任务浏览',
  'dbd_do_task_txt':'执行任务',
  'dbd_history_task_txt':'历史任务',

  'dbd_purchasing_management_txt':'订货管理',
  'dbd_safe_instock_num_txt':'库存提醒',
  'dbd_start_purchasing_txt':'发起订货',
  'dbd_purchasing_order_management_txt':'单据管理',
  'dbd_receving_management_txt':'收货管理',

  'dbd_report_center_txt':'报告中心',
  'dbd_report1_txt':'报告一',
  'dbd_report2_txt':'报告二',
  'add_space_page_title': 'ADDSPACE',
  'space_title_txt': 'Add Space',
  'space_code_txt': 'Space Code',
  'space_name_txt': 'Space Name',
  'space_type_txt': 'Space Type',
  'space_temperature_txt': 'Space temperature',
  'space_status_txt': 'Space Status',
  'position_title_txt': 'Add Position',
  'position_code_txt': 'Position Code',
  'position_name_txt': 'Position Name',
  'position_status_txt': 'Position Status',
  'shelf_title_txt': 'New Shelf',
  'shelf_code_txt': 'Shelf Code',
  'shelf_name_txt': 'Shelf Name',
  'shelf_status_txt': 'Status',
  'shelf_row_txt': 'Shelf Rows',
  'shelf_column_txt': 'Shelf Columns',
  'location_title_txt': 'New Location In The Position',
  'add_location_page_title': 'New Location',
  'location_code': 'Location Code',
  'location_barcode': 'Location Barcode',
  'location_status': 'Location Status',
  'set_default_location_txt': 'Set Default Location For Shelf',

  'bm_assembly_space_txt': 'Assembly Space',
  'bm_stockup_space_txt': 'Stockup Space',
  'bm_packs_space_txt': 'Packs Space',
  'bm_delivery_space_txt': 'Delivery Space',
  'bm_parts_space_txt': 'Parts Space',
  'bm_shipping_space_txt': 'Shipping Space',
  'bm_transfer_space_txt': 'Transfer Space'
};
