export const ZH: {} = {
  'BASE_INFO_TITLE': '基础信息',
  'save_txt': '保存',
  'cancel_txt': '取消',
  'go_back_txt': '返回',
  'detail_txt': '详情',
  'start_txt': '启动',
  'stop_txt': '停止',
  'new_txt': 'New',

  'login_page_title': '登录',
  'welcome_text':'欢迎',
  'login_text':'登录',
  'ph_name_txt':'请输入账号',
  'ph_pwd_txt':'请输入密码',

  'dashboard_page_title': '主页',
  'stocking_txt':'仓库管理',
  'in_stock_txt':'在库管理',
  'dbd_space_management_txt':'库区管理',
  'dbd_shelf_management_txt':'货架管理',
  'dbd_location_management_txt':'货位管理',
  'dbd_instock_info_txt':'在库信息',
  'dbd_inbound_txt':'入库管理',
  'dbd_outbound_txt':'出库管理',
  'dbd_checking_txt':'盘点管理',
  'dbd_wastage_txt':'损耗管理',
  'dbd_item_move_txt':'移动商品',

  'dbd_task_management_txt':'任务管理',
  'dbd_task_list_txt':'任务浏览',
  'dbd_do_task_txt':'执行任务',
  'dbd_history_task_txt':'历史任务',
  'dbd_all_task_txt': '全部任务',
  'dbd_backorder_txt': '延时任务',

  'dbd_purchasing_management_txt':'订货管理',
  'dbd_safe_instock_num_txt':'库存提醒',
  'dbd_start_purchasing_txt':'发起订货',
  'dbd_purchasing_order_management_txt':'单据管理',
  'dbd_receving_management_txt':'收货管理',

  'dbd_report_center_txt':'报告中心',
  'dbd_report1_txt':'报告一',
  'dbd_report2_txt':'报告二',

  'add_space_page_title': '新建库区库位信息',
  'space_title_txt': '新建库区',
  'space_code_txt': '库区编码',
  'space_name_txt': '库区名称',
  'space_type_txt': '库区类型',
  'space_temperature_txt': '温区类型',
  'space_status_txt': '库区状态',
  'position_title_txt': '新建库位',
  'position_code_txt': '库位编码',
  'position_name_txt': '库位名称',
  'position_status_txt': '库位状态',
  'shelf_title_txt': '新增货架',
  'shelf_code_txt': '货架编码',
  'shelf_name_txt': '货架名称',
  'shelf_status_txt': '货架状态',
  'shelf_row_txt': '货架层数',
  'shelf_column_txt': '货架列数',
  'location_title_txt': '库位新增货位',
  'bm_assembly_space_txt': '组装区',
  'bm_stockup_space_txt': '备货区',
  'bm_packs_space_txt': '打包区',
  'bm_delivery_space_txt': '发货区',
  'bm_parts_space_txt': '配件区',
  'bm_shipping_space_txt': '物流区',
  'bm_transfer_space_txt': '调拨区',

  'add_location_page_title': '新建货位信息',
  'location_code_txt': '货位编码',
  'location_barcode_txt': '货位条码',
  'location_status_txt': '货位状态',
  'set_default_location_txt': '创建货架货位方式',

  'im_inbound_title_txt': '单品入库',
  'im_outbound_title_txt': '单品出库',
  'im_wastage_title_txt': '录入损耗',
  'im_item_instock_detail': '商品在库详情',
  'im_input_location_code_txt': '输入库位码',
  'im_input_barcode_txt': 'BARCODE',
  'im_sku_txt': 'SKU',
  'im_num_txt': '数量',
  'im_production_date_txt': '生产日期',
  'im_expiration_date_txt': '过保日期',
  'im_shelf_life_txt': '保质期',
  'im_memo_txt': '备注',
  'im_location_txt': '货位',
  'im_batch_txt': '批次',
  'im_item_name_txt': '商品名称',

  'filter_ordercd_txt': '单号',
  'filter_operator_txt': '操作人',
  'filter_operdate_txt': '操作日期',
  'filter_No_txt': '#',
  'filter_status_txt': '状态',
  'filter_reason_txt': '原因',
  'filter_reason_type_txt': '原因类型',
  'filter_search_txt': 'Search',
  'filter_clear_txt': 'Clear',
  'filter_actions_txt': 'actions',
  'filter_customer_txt': '客户',
  'filter_itemname_txt': '品名',
  'filter_sku_txt': 'SKU',
  'filter_num_txt': 'Qty',
  'filter_approved_txt': '确认数',
  'filter_arithmetic_txt': '差',
  'filter_package_txt': '包',
  'filter_pallet_txt': '拍子(l*w[in*in])',
  'filter_height_txt': '高(in)',
  'filter_weight_txt': '重(lb)',
  'filter_location_txt': '存入位置',
  'filter_trackNumber_txt': '追踪单号',
  

  'btn_report_txt': '报告',
  'btn_detail_txt': '明细',
  'btn_continue_txt': '继续',
  'btn_pause_txt': '暂停',
  'btn_checking_completed_txt': '盘点完成',
  'btn_go_txt': '执行',
  'btn_signin_txt': '抢单',
  'btn_senttoCSStaff_txt': '发送客服处理',
  'btn_createbackorder_txt': '创建backorder',
  'btn_outbound_txt': '确认出库',
  'btn_confirm_txt': '确认',

  'btn_toShipArea_txt': '存入物流区',
  'btn_photo_txt': 'Photo',
  'btn_print_txt': 'Print',
  'btn_shipOutBound_txt': '物流出库',

  'ttl_setSize_txt': '设置包裹长宽[in*in]',

  'startTitle_txt': '开单',
  'outboundTitle_txt': '出货',
  'packageTitle_txt': '打包',
  'agentLogisticTitle_txt': '物流提货',
  'shipping_txt': '发车',
};
